# Generated by Django 3.0.1 on 2019-12-28 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('Unique_Squirrel_ID', models.CharField(max_length=30, unique=True)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=30)),
                ('Date', models.DateField(blank=True, default=django.utils.timezone.now, max_length=30, null=True)),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='Adult', max_length=30)),
                ('Primary_fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], default='Gray', max_length=30)),
                ('Location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default='Ground Plane', max_length=30)),
                ('Specific_location', models.CharField(blank=True, max_length=30)),
                ('Running', models.NullBooleanField(help_text='run')),
                ('Chasing', models.NullBooleanField(help_text='Chase')),
                ('Climbing', models.NullBooleanField(help_text='Climb')),
                ('Eating', models.NullBooleanField(help_text='Eat')),
                ('Foraging', models.NullBooleanField(help_text='Forage')),
                ('Other_Activities', models.CharField(help_text='Others', max_length=30)),
                ('Kuks', models.NullBooleanField(help_text='Kuks')),
                ('Quaas', models.NullBooleanField(help_text='Quaas')),
                ('Moans', models.NullBooleanField(help_text='Moans')),
                ('Tail_flags', models.NullBooleanField(help_text='Tailflags')),
                ('Tail_twitches', models.NullBooleanField(help_text='Tail twitches')),
                ('Approaches', models.NullBooleanField(help_text='Approaches')),
                ('Indifferent', models.NullBooleanField(help_text='Indifferent')),
                ('Runs_from', models.NullBooleanField(help_text='Runs from')),
            ],
        ),
    ]
